### PR TITLE
Add the ability to hide scribble on certain slides

### LINKED ISSUE #158: Feature request: To disable scribble on a specific slide
Scribble is a fantastic feature. But it will be nice if we can disable the scribble feature on a few selective slides like the title slide.

Thank you

### PR DESCRIPTION
**Pull request by mattwarkentin**
Fixes #158

This small PR allows users to add the `'hide-scribble'` class to any slide (including the title slide) to disable scribble entirely. With the `'hide-scribble'` class, the toolbox is hidden and cannot be toggled back to visible, and any drawing is disabled. In other words, the toolbox is hidden and pressing 'S' does nothing.

### CODE REVIEW

**Comment by mattwarkentin** [comment]
I think the current PR addresses the original request:
> But it will be nice if we can disable the scribble feature on a few selective slides like the title slide.

But I'm not sure it satisfies your recent comment:
> ...we'd want to ensure the controls still appear when summoned via the keyboard shortcuts

I have made it so the addition of the `'hide-scribble'` class disables scribble entirely for the specific slide. But your comment sounds like you want the controls hidden, but that they could be recovered by the keyboard shortcut.

I will wait to hear your thoughts and we can iterate as needed.

**Review by gadenbuie — APPROVED** [review]
This looks great and I think it's the right way to go. It's easiest and definitely cleanest to completely disable scribble on these slides.

One small question: should the class be `disable-scribble` or `no-scribble` since it's completely disabled for the slide (rather than just hidden)?

**Comment by mattwarkentin** [comment]
I'm pretty neutral on the class name - maybe a slight preference for `no-scribble` because of its brevity. If you agree, I can make this change quickly.

**Comment by mattwarkentin** [comment]
Done! I also made an attempt at documenting the usage in the showcasing slide deck, because, well, if it's not documented it doesn't exist. I think that is how the saying goes.

**Comment by gadenbuie** [comment]
Thanks Matt! I'm going to wait a little bit to merge this once #163 lands (i.e. once the current version makes it onto CRAN 🤞)

**Pull request merged**
